// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MadeWithMv","status":false,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"true","Made with MV Image":"nenga_hanko","Show Custom Splash":"false","Custom Image":"nenga_hanko","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"TMMoveEx","status":true,"description":"壁衝突音やリージョンによる通行設定などの機能を追加します。","parameters":{"passableRegionId":"251","dontPassRegionId":"252","seKnockWall":"<name:Blow1><volume:90><pitch:100>","knockWallPan":"75","knockWallInterval":"30","turnKeyCode":"83","movableRegion1":"","movableRegion2":"","movableRegion3":"","movableRegion4":"","movableRegion5":"","movableRegion6":"","movableRegion7":"","movableRegion8":"","movableRegion9":"","movableRegion10":""}},
{"name":"InfoWindow","status":true,"description":"情報表示ウィンドウをメニュー画面に追加するプラグイン","parameters":{}},
{"name":"TMAutoNewGame","status":false,"description":"起動時に自動ではじめからゲームを開始します。\nWeb用ミニゲームなど、タイトル画面が不要な場合などにどうぞ。","parameters":{"autoNewGame":"1","firstLimited":"2","allwaysOnTop":"0","autoDevTool":"1","autoContinueCommand":"自動コンティニュー","blockKey":"control"}},
{"name":"Tweet","status":true,"description":"ツイートする","parameters":{"url":"","via":""}}
];
